/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export interface IApiElementModelBase {
  readonly id: string;
  readonly contentType: string;
}

export interface TestCompositionPropertiesModel {
  /** @nullable */
  sharedToggle?: boolean | null;
  /** @nullable */
  sharedString?: string | null;
}

export type TestCompositionElementModelContentType = typeof TestCompositionElementModelContentType[keyof typeof TestCompositionElementModelContentType];


export const TestCompositionElementModelContentType = {
  testComposition: 'testComposition',
} as const;

export type TestCompositionElementModel = Omit<IApiElementModelBase, 'contentType'> & {
  properties?: TestCompositionPropertiesModel;
  contentType: TestCompositionElementModelContentType;
};

export interface RichTextModel {
  markup: string;
  blocks: (ApiBlockItemModel | ApiBlockGridItemModel)[];
}

export interface TestComposition2PropertiesModel {
  /** @nullable */
  sharedRadiobox?: string | null;
  sharedRichText?: RichTextModel;
}

export type TestComposition2ElementModelContentType = typeof TestComposition2ElementModelContentType[keyof typeof TestComposition2ElementModelContentType];


export const TestComposition2ElementModelContentType = {
  testComposition2: 'testComposition2',
} as const;

export type TestComposition2ElementModel = Omit<IApiElementModelBase, 'contentType'> & {
  properties?: TestComposition2PropertiesModel;
  contentType: TestComposition2ElementModelContentType;
};

export interface BlockSettingsPropertiesModel {
  /** @nullable */
  anchorId?: string | null;
}

export type BlockSettingsElementModelContentType = typeof BlockSettingsElementModelContentType[keyof typeof BlockSettingsElementModelContentType];


export const BlockSettingsElementModelContentType = {
  blockSettings: 'blockSettings',
} as const;

export type BlockSettingsElementModel = Omit<IApiElementModelBase, 'contentType'> & {
  properties?: BlockSettingsPropertiesModel;
  contentType: BlockSettingsElementModelContentType;
};

export type TestBlock2PropertiesModel = TestCompositionPropertiesModel & ({
  /** @nullable */
  thisIsTestBlock2?: string | null;
});

export type TestBlock2ElementModelContentType = typeof TestBlock2ElementModelContentType[keyof typeof TestBlock2ElementModelContentType];


export const TestBlock2ElementModelContentType = {
  testBlock2: 'testBlock2',
} as const;

export type TestBlock2ElementModel = Omit<IApiElementModelBase, 'contentType'> & {
  properties?: TestBlock2PropertiesModel;
  contentType: TestBlock2ElementModelContentType;
};

export interface ApiContentStartItemModel {
  id: string;
  path: string;
}

export interface ApiContentRouteModel {
  path: string;
  /** @nullable */
  queryString?: string | null;
  startItem: ApiContentStartItemModel;
}

export type IApiContentModelBase = Omit<IApiElementModelBase, 'contentType'> & ({
  readonly id: string;
  readonly contentType: string;
  /** @nullable */
  readonly name?: string | null;
  readonly createDate: string;
  readonly updateDate: string;
  readonly route: ApiContentRouteModel;
});

export interface PickedColorModel {
  value: string;
  label: string;
}

export type LinkTypeModel = typeof LinkTypeModel[keyof typeof LinkTypeModel];


export const LinkTypeModel = {
  Content: 'Content',
  Media: 'Media',
  External: 'External',
} as const;

export interface ApiLinkModel {
  /** @nullable */
  readonly url?: string | null;
  /** @nullable */
  readonly queryString?: string | null;
  /** @nullable */
  readonly title?: string | null;
  /** @nullable */
  readonly target?: string | null;
  /** @nullable */
  readonly destinationId?: string | null;
  /** @nullable */
  readonly destinationType?: string | null;
  readonly route?: ApiContentRouteModel | null;
  linkType: LinkTypeModel;
  /** @nullable */
  readonly culture?: string | null;
}

export interface ApiBlockGridModel {
  gridColumns: number;
  items: ApiBlockGridItemModel[];
}

export interface ApiBlockListModel {
  items: (ApiBlockItemModel | ApiBlockGridItemModel)[];
}

export interface ImageFocalPointModel {
  left: number;
  top: number;
}

export interface ImageCropCoordinatesModel {
  x1: number;
  y1: number;
  x2: number;
  y2: number;
}

export interface ImageCropModel {
  /** @nullable */
  alias?: string | null;
  width: number;
  height: number;
  coordinates?: ImageCropCoordinatesModel;
}

export type IApiMediaWithCropsModelProperties = {[key: string]: unknown | null};

export interface IApiMediaWithCropsModel {
  readonly id: string;
  readonly name: string;
  readonly mediaType: string;
  readonly url: string;
  /** @nullable */
  readonly extension?: string | null;
  /** @nullable */
  readonly width?: number | null;
  /** @nullable */
  readonly height?: number | null;
  /** @nullable */
  readonly bytes?: number | null;
  readonly properties: IApiMediaWithCropsModelProperties;
  focalPoint?: ImageFocalPointModel;
  /** @nullable */
  readonly crops?: readonly ImageCropModel[] | null;
}

export interface ApiImageCropperValueModel {
  url: string;
  focalPoint?: ImageFocalPointModel;
  /** @nullable */
  crops?: ImageCropModel[] | null;
}

export type TestPagePropertiesModel = TestCompositionPropertiesModel & TestComposition2PropertiesModel & ({
  /** @nullable */
  textString?: string | null;
  /** @nullable */
  textArea?: string | null;
  /** @nullable */
  datePickerWithTime?: string | null;
  /** @nullable */
  datePicker?: string | null;
  /** @nullable */
  toggle?: boolean | null;
  /** @nullable */
  numeric?: number | null;
  /** @nullable */
  decimal?: number | null;
  /** @nullable */
  slider?: number | null;
  /** @nullable */
  tags?: string[] | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  dateOnly?: string | null;
  /** @nullable */
  timeOnly?: string | null;
  /** @nullable */
  dateTimeUnspecified?: string | null;
  /** @nullable */
  dateTimeWithTimeZone?: string | null;
  colorPicker?: PickedColorModel;
  contentPicker?: IApiContentModel;
  /** @nullable */
  eyeDropperColorPicker?: string | null;
  /** @nullable */
  urlPicker?: ApiLinkModel[] | null;
  /** @nullable */
  multinodeTreepicker?: IApiContentModel[] | null;
  richText?: RichTextModel;
  blockGrid?: ApiBlockGridModel;
  /** @nullable */
  markdown?: string | null;
  /** @nullable */
  userPicker?: number | null;
  blockList?: ApiBlockListModel;
  /** @nullable */
  checkboxList?: string[] | null;
  /** @nullable */
  dropdown?: string | null;
  /** @nullable */
  radiobox?: string | null;
  /** @nullable */
  repeatableTextstrings?: string[] | null;
  /** @nullable */
  mediaPicker?: IApiMediaWithCropsModel[] | null;
  /** @nullable */
  uploadFile?: string | null;
  imageCropper?: ApiImageCropperValueModel;
});

export type TestPageContentModelContentType = typeof TestPageContentModelContentType[keyof typeof TestPageContentModelContentType];


export const TestPageContentModelContentType = {
  testPage: 'testPage',
} as const;

export type TestPageContentModel = Omit<IApiContentModelBase, 'contentType'> & {
  properties?: TestPagePropertiesModel;
  contentType: TestPageContentModelContentType;
};

export type TestPageInvariantPropertiesModel = TestCompositionPropertiesModel & TestComposition2PropertiesModel & ({
  /** @nullable */
  textString?: string | null;
  /** @nullable */
  textArea?: string | null;
  /** @nullable */
  datePickerWithTime?: string | null;
  /** @nullable */
  datePicker?: string | null;
  /** @nullable */
  toggle?: boolean | null;
  /** @nullable */
  numeric?: number | null;
  /** @nullable */
  decimal?: number | null;
  /** @nullable */
  slider?: number | null;
  /** @nullable */
  tags?: string[] | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  dateOnly?: string | null;
  /** @nullable */
  timeOnly?: string | null;
  /** @nullable */
  dateTimeUnspecified?: string | null;
  /** @nullable */
  dateTimeWithTimeZone?: string | null;
  colorPicker?: PickedColorModel;
  contentPicker?: IApiContentModel;
  /** @nullable */
  eyeDropperColorPicker?: string | null;
  /** @nullable */
  urlPicker?: ApiLinkModel[] | null;
  /** @nullable */
  multinodeTreepicker?: IApiContentModel[] | null;
  richText?: RichTextModel;
  blockGrid?: ApiBlockGridModel;
  /** @nullable */
  markdown?: string | null;
  /** @nullable */
  userPicker?: number | null;
  blockList?: ApiBlockListModel;
  /** @nullable */
  checkboxList?: string[] | null;
  /** @nullable */
  dropdown?: string | null;
  /** @nullable */
  radiobox?: string | null;
  /** @nullable */
  repeatableTextstrings?: string[] | null;
  /** @nullable */
  mediaPicker?: IApiMediaWithCropsModel[] | null;
  /** @nullable */
  uploadFile?: string | null;
  imageCropper?: ApiImageCropperValueModel;
});

export type TestPageInvariantContentModelContentType = typeof TestPageInvariantContentModelContentType[keyof typeof TestPageInvariantContentModelContentType];


export const TestPageInvariantContentModelContentType = {
  testPageInvariant: 'testPageInvariant',
} as const;

export type TestPageInvariantContentModel = Omit<IApiContentModelBase, 'contentType'> & {
  properties?: TestPageInvariantPropertiesModel;
  contentType: TestPageInvariantContentModelContentType;
};

export type IApiContentModel = TestPageContentModel | TestPageInvariantContentModel;

export type TestBlockPropertiesModel = TestCompositionPropertiesModel & ({
  /** @nullable */
  string?: string | null;
  /** @nullable */
  multinodeTreepicker?: IApiContentModel[] | null;
  blocks?: ApiBlockListModel;
});

export type TestBlockElementModelContentType = typeof TestBlockElementModelContentType[keyof typeof TestBlockElementModelContentType];


export const TestBlockElementModelContentType = {
  testBlock: 'testBlock',
} as const;

export type TestBlockElementModel = Omit<IApiElementModelBase, 'contentType'> & {
  properties?: TestBlockPropertiesModel;
  contentType: TestBlockElementModelContentType;
};

export type IApiElementModel = TestCompositionElementModel | TestComposition2ElementModel | BlockSettingsElementModel | TestBlock2ElementModel | TestBlockElementModel;

export interface ApiBlockItemModel {
  content: IApiElementModel;
  settings?: IApiElementModel;
}

export type ApiBlockGridItemModel = ApiBlockItemModel & {
  rowSpan?: number;
  columnSpan?: number;
  areaGridColumns?: number;
  areas?: ApiBlockGridAreaModel[];
};

export interface ApiBlockGridAreaModel {
  alias: string;
  rowSpan: number;
  columnSpan: number;
  items: ApiBlockGridItemModel[];
}

export interface ProblemDetails {
  /** @nullable */
  type?: string | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  status?: number | null;
  /** @nullable */
  detail?: string | null;
  /** @nullable */
  instance?: string | null;
  [key: string]: unknown;
}

export type HttpValidationProblemDetails = ProblemDetails & {
  errors?: {[key: string]: string[]};
  [key: string]: unknown;
};

export type IApiContentResponseModelBaseCultures = {[key: string]: ApiContentRouteModel};

export type IApiContentResponseModelBase = Omit<IApiContentModelBase, 'contentType'> & ({
  readonly id: string;
  readonly contentType: string;
  /** @nullable */
  readonly name?: string | null;
  readonly createDate: string;
  readonly updateDate: string;
  readonly route: ApiContentRouteModel;
  readonly cultures: IApiContentResponseModelBaseCultures;
});

export type TestPageContentResponseModelContentType = typeof TestPageContentResponseModelContentType[keyof typeof TestPageContentResponseModelContentType];


export const TestPageContentResponseModelContentType = {
  testPage: 'testPage',
} as const;

export type TestPageContentResponseModel = Omit<IApiContentResponseModelBase & TestPageContentModel, 'contentType'> & {
  contentType: TestPageContentResponseModelContentType;
};

export type TestPageInvariantContentResponseModelContentType = typeof TestPageInvariantContentResponseModelContentType[keyof typeof TestPageInvariantContentResponseModelContentType];


export const TestPageInvariantContentResponseModelContentType = {
  testPageInvariant: 'testPageInvariant',
} as const;

export type TestPageInvariantContentResponseModel = Omit<IApiContentResponseModelBase & TestPageInvariantContentModel, 'contentType'> & {
  contentType: TestPageInvariantContentResponseModelContentType;
};

export type IApiContentResponseModel = TestPageContentResponseModel | TestPageInvariantContentResponseModel;

export type IApiMediaWithCropsResponseModelProperties = {[key: string]: unknown | null};

export interface IApiMediaWithCropsResponseModel {
  readonly id: string;
  readonly name: string;
  readonly mediaType: string;
  readonly url: string;
  /** @nullable */
  readonly extension?: string | null;
  /** @nullable */
  readonly width?: number | null;
  /** @nullable */
  readonly height?: number | null;
  /** @nullable */
  readonly bytes?: number | null;
  readonly properties: IApiMediaWithCropsResponseModelProperties;
  focalPoint: ImageFocalPointModel;
  /** @nullable */
  readonly crops?: readonly ImageCropModel[] | null;
  readonly path: string;
  readonly createDate: string;
  readonly updateDate: string;
}

export interface PagedIApiContentResponseModel {
  total: number;
  items: IApiContentResponseModel[];
}

export interface PagedIApiMediaWithCropsResponseModel {
  total: number;
  items: IApiMediaWithCropsResponseModel[];
}

export type GetContent20Params = {
/**
 * Specifies the content items to fetch. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
 */
fetch?: string;
/**
 * Defines how to filter the fetched content items. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
 */
filter?: string[];
/**
 * Defines how to sort the found content items. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
 */
sort?: string[];
/**
 * Specifies the number of found content items to skip. Use this to control pagination of the response.
 */
skip?: number;
/**
 * Specifies the number of found content items to take. Use this to control pagination of the response.
 */
take?: number;
/**
 * Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
 */
expand?: string;
/**
 * Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
 */
fields?: string;
};

export type GetContentItemByPath20Params = {
/**
 * Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
 */
expand?: string;
/**
 * Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
 */
fields?: string;
};

export type GetContentItemById20Params = {
/**
 * Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
 */
expand?: string;
/**
 * Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
 */
fields?: string;
};

export type GetContentItems20Params = {
id?: string[];
/**
 * Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
 */
expand?: string;
/**
 * Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
 */
fields?: string;
};

export type GetMedia20Params = {
/**
 * Specifies the media items to fetch. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
 */
fetch?: string;
/**
 * Defines how to filter the fetched media items. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
 */
filter?: string[];
/**
 * Defines how to sort the found media items. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
 */
sort?: string[];
/**
 * Specifies the number of found media items to skip. Use this to control pagination of the response.
 */
skip?: number;
/**
 * Specifies the number of found media items to take. Use this to control pagination of the response.
 */
take?: number;
/**
 * Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
 */
expand?: string;
/**
 * Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
 */
fields?: string;
};

export type GetMediaItemByPath20Params = {
/**
 * Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
 */
expand?: string;
/**
 * Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
 */
fields?: string;
};

export type GetMediaItemById20Params = {
/**
 * Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
 */
expand?: string;
/**
 * Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
 */
fields?: string;
};

export type GetMediaItems20Params = {
id?: string[];
/**
 * Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
 */
expand?: string;
/**
 * Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
 */
fields?: string;
};

export const getContent20 = (
    params?: GetContent20Params, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PagedIApiContentResponseModel>> => {
    return axios.get(
      `http://localhost:34962/umbraco/delivery/api/v2/content`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const getContentItemByPath20 = (
    path: string,
    params?: GetContentItemByPath20Params, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<IApiContentResponseModel>> => {
    return axios.get(
      `http://localhost:34962/umbraco/delivery/api/v2/content/item/${path}`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const getContentItemById20 = (
    id: string,
    params?: GetContentItemById20Params, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<IApiContentResponseModel>> => {
    return axios.get(
      `http://localhost:34962/umbraco/delivery/api/v2/content/item/${id}`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const getContentItems20 = (
    params?: GetContentItems20Params, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<IApiContentResponseModel[]>> => {
    return axios.get(
      `http://localhost:34962/umbraco/delivery/api/v2/content/items`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const getMedia20 = (
    params?: GetMedia20Params, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PagedIApiMediaWithCropsResponseModel>> => {
    return axios.get(
      `http://localhost:34962/umbraco/delivery/api/v2/media`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const getMediaItemByPath20 = (
    path: string,
    params?: GetMediaItemByPath20Params, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<IApiMediaWithCropsResponseModel>> => {
    return axios.get(
      `http://localhost:34962/umbraco/delivery/api/v2/media/item/${path}`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const getMediaItemById20 = (
    id: string,
    params?: GetMediaItemById20Params, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<IApiMediaWithCropsResponseModel>> => {
    return axios.get(
      `http://localhost:34962/umbraco/delivery/api/v2/media/item/${id}`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const getMediaItems20 = (
    params?: GetMediaItems20Params, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<IApiMediaWithCropsResponseModel[]>> => {
    return axios.get(
      `http://localhost:34962/umbraco/delivery/api/v2/media/items`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export type GetContent20Result = AxiosResponse<PagedIApiContentResponseModel>
export type GetContentItemByPath20Result = AxiosResponse<IApiContentResponseModel>
export type GetContentItemById20Result = AxiosResponse<IApiContentResponseModel>
export type GetContentItems20Result = AxiosResponse<IApiContentResponseModel[]>
export type GetMedia20Result = AxiosResponse<PagedIApiMediaWithCropsResponseModel>
export type GetMediaItemByPath20Result = AxiosResponse<IApiMediaWithCropsResponseModel>
export type GetMediaItemById20Result = AxiosResponse<IApiMediaWithCropsResponseModel>
export type GetMediaItems20Result = AxiosResponse<IApiMediaWithCropsResponseModel[]>
