name: Build and release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
    branches:
      - main
      - develop
      - feature/pipelines

env:
  VERSION: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || null }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set version
      if: ${{ !env.VERSION }}
      run: |
        calculatedSha=$(git rev-parse --short ${{ github.sha }})
        echo "VERSION=0.0.0-$calculatedSha" >> $GITHUB_ENV

    - name: Setup npm
      uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x

    - name: Build project
      run: dotnet build src/UmbracoDeliveryApiExtensions/UmbracoDeliveryApiExtensions.csproj
           -c Release
           -o ${{env.DOTNET_ROOT}}/package/
           /p:ContinuousIntegrationBuild=true
           ${{ format('/p:Version={0}', env.VERSION) }}

    - name: Upload package as artifact
      uses: actions/upload-artifact@v3
      with:
        name: artifact
        path: |
          ${{env.DOTNET_ROOT}}/package/*.nupkg
          ${{env.DOTNET_ROOT}}/package/*.snupkg


  release:
    name: Release to NuGet
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    needs: build
    steps:

    - name: Download artifact from build
      uses: actions/download-artifact@v3
      with:
        name: artifact

    - name: Release to Nuget
      run: dotnet nuget push "*.nupkg" --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
